### ISSUE TITLE
Spelling error bug in error_check.r

### ISSUE THREAD

**Issue by stablemarkets** [stablemarkets/ChiRP#12]
Issue submitted by Eric Ginsberg via email. Integer is spelled incorrectly in error_check.r - Non-fatal. Shouldn't affect results or stop code execution for ZDPMix, NDPMix, or fDPMix

Spelling error 'interger' should be 'integer'. 
```
  if(! class(func_args$d_train[,y]) %in% c('numeric', 'interger') ){
    stop("ERROR: outcome is not numeric")
```

**Comment by lagvier** [comment]
can make correction

**Comment by stablemarkets** [comment]
Sure thanks. If you make the change and submit a pull request, I'll review and merge.

**Comment by stablemarkets** [comment]
Merged PR fixing this: https://github.com/stablemarkets/ChiRP/pull/13. Closing issue.
